### PR TITLE
:left_right_arrow: Ensure time range is inclusive

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
Does this need reviewing? I see a couple of empty tests...

**Comment by neilbmclaughlin** [comment]
Sorry, you beat me to it. Wanted to flag it as WIP.

**Comment by st3v3nhunt** [comment]
Label added. Feel free to change the wording or the colour

**Comment by neilbmclaughlin** [comment]
Removed the WIP label so ready for review. Adding/removing labels doesn't seem to trigger a slack notification.

I've left the pending (aka empty) test as a reminder of work we need to do but not for the lab session.

I've also lowered the coverage thresholds so we can go back to running lint/mocha as part of the commit.

**Pull request merged**
